"""Adds assignment, cat, exams in enrollment

Revision ID: 2a19993b1073
Revises: 9c06ec07361b
Create Date: 2025-03-28 10:00:33.495879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a19993b1073'
down_revision = '9c06ec07361b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cat_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exam_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('exam_score')
        batch_op.drop_column('cat_score')
        batch_op.drop_column('assignment_score')

    # ### end Alembic commands ###
