"""Adds relationship to performance

Revision ID: 87664ff11536
Revises: 2a19993b1073
Create Date: 2025-03-28 15:03:19.321885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87664ff11536'
down_revision = '2a19993b1073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
