"""Adds vedio section

Revision ID: d8dbc136a9be
Revises: c3ffc9728f81
Create Date: 2025-03-25 20:25:27.594255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dbc136a9be'
down_revision = 'c3ffc9728f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=505), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
