"""Adds submission table and its relationship

Revision ID: e5e46509a82f
Revises: d8dbc136a9be
Create Date: 2025-03-27 14:41:11.631089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e46509a82f'
down_revision = 'd8dbc136a9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('submission_text',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('submission_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('document_url')

    # ### end Alembic commands ###
